<a href="https://colab.research.google.com/github/junya-ph/report/blob/making_report/%E5%BF%9C%E7%94%A8%E6%95%B0%E5%AD%A6%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 第１章：線形代数

線形代数は、ベクトルや行列などを扱う数学の分野の一つである。深層学習では多くの数値を扱う必要があり、線形代数を利用すれば多くの数値の処理を簡潔に記述することができる。線形代数における数値のまとめ方は、スカラー、ベクトル、行列、テンソルがある。スカラーとは、1、-2、などの通常の数値である。ベクトルとは、スカラーを直線上に並べたものである。ベクトルには、数値を縦に並べる縦ベクトルと数値を横に並べる横ベクトルがある。行列とは、スカラーを格子状に並べたものである。行列において、横方向のスカラーの並びを行、縦方向のスカラーの並びを列という。テンソルとは、スカラーを複数の次元に並べたものである。

ベクトルの計算

In [2]:
import numpy as np
a = np.array([1, 6, 3])
b = np.array([5, 2, 4])

print(a+b) #ベクトル同士の足し算
print(a-b) #ベクトル同士の引き算
print(7*a) #ベクトルaを7倍

[6 8 7]
[-4  4 -1]
[ 7 42 21]


行列の計算

In [5]:
c = np.array([[2, 1],[5, 3]])
d = np.array([[1, 4],[1, 5]])
print(c+d) #行列同士の足し算
print(c-d) #行列同士の引き算

[[3 5]
 [6 8]]
[[ 1 -3]
 [ 4 -2]]
